# Generated by Django 6.0.6 on 2026-10-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_siteconfig_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_pix', models.CharField(default='pereelt@gmail.com', help_text='Chave PIX que será exibida para o cliente realizar o pagamento.', max_length=255, verbose_name='Chave PIX (E-mail, CPF, CNPJ ou Aleatória)')),
                ('nome_titular', models.CharField(default='Supermercado Itatingax', help_text='Nome da conta que aparecerá no comprovante do cliente.', max_length=100, verbose_name='Nome do Titular/Recebedor')),
                ('taxa_estatal_percentual', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentagem de taxa cobrada no checkout PIX (ex: 10.00 para +10%).', max_digits=5, verbose_name='Taxa de Submissão Estatal (%)')),
                ('instrucao_pagamento', models.TextField(default='Envie o valor exato em Reais. O processamento estatal pode levar até 3 dias úteis para homologação fiscal.', help_text='Texto explicativo mostrado na parte inferior do modal PIX.', verbose_name='Mensagem / Aviso do Modal')),
            ],
            options={
                'verbose_name': 'Configuração do PIX',
                'verbose_name_plural': 'Configuração do PIX',
            },
        ),
    ]
