# Generated by Django 6.0.6 on 2026-10-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_configuracaopix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaopix',
            name='chave_pix',
            field=models.CharField(default='SUA_CHAVE_PIX_AQUI', help_text='Chave PIX que será exibida para o cliente realizar o pagamento.', max_length=255, verbose_name='Chave PIX (E-mail, CPF, CNPJ ou Aleatória)'),
        ),
    ]
