# Generated by Django 6.0.6 on 2026-10-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_configuracaopix_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaopix',
            name='rotulo_taxa_pix',
            field=models.CharField(default='Taxa de Processamento Fiat (PIX)', help_text='Texto que aparece antes do valor da taxa. Ex: Taxa de Processamento Fiat, Taxa de Submissão Estatal, Taxa de Conveniência', max_length=100, verbose_name='Rótulo / Nome da Taxa'),
        ),
        migrations.AlterField(
            model_name='configuracaopix',
            name='instrucao_pagamento',
            field=models.TextField(default='Envie o valor exato em Reais.', help_text='Texto explicativo mostrado na parte inferior do modal PIX.', verbose_name='Mensagem / Aviso do Modal'),
        ),
        migrations.AlterField(
            model_name='configuracaopix',
            name='taxa_estatal_percentual',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentagem de taxa cobrada no checkout PIX (ex: 10.00 para +10%).', max_digits=5, verbose_name='Taxa da Operação Fiat (%)'),
        ),
    ]
