# Generated by Django 6.0.6 on 2026-10-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configuracaopix_rotulo_taxa_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador único para o JS. Ex: prod_cafe_500', max_length=50, null=True, unique=True),
        ),
    ]
